### ISSUE TITLE
“Circular dependency! Loop in processing…”

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1138]
Apparently, Refined Storage can’t handle both dust to ingot and ingot to block recipes.

**Comment by raoulvdberge** [comment]
@way2muchnoise we should really make a wiki article on this message, people keep asking about it

**Comment by VT-14** [comment]
The problem is that you have a loop.  9 Iron Ingots can be made from 1 Iron Block, and 1 Iron Block is made from 9 Iron Ingots; and/or you have 1 Iron Ingot can be made by smelting 1 Iron Dust, which can be made by crushing 1 Iron Ingot.

You can fix this by removing any of your two-way recipes.  They are usually redundant (why would you need to know how to craft ingots from blocks if you are storing ingots?)

Also, [please search before opening a new issue.](https://github.com/raoulvdberge/refinedstorage/issues?utf8=%E2%9C%93&q=Circular%20dependency)

**Comment by raoulvdberge** [comment]
@PapiDimmi why are you downvoting his explanation?

**Comment by PapiDimmi** [comment]
Because I disagree that it’s redundant.

**Comment by brad811** [comment]
I'm having this problem as well. My issue is stuff like inferium, which can be converted back and forth depending on what is needed.
