### ISSUE TITLE
Only the topmost disk in the disk manipulator is manipulated

### ISSUE THREAD

**Issue by ghost** [raoulvdberge/refinedstorage#1147]
**Minecraft version**: 1.10.2
**Refined Storage version**: 1.2.25
**Forge version**: 12.18.3.2272

**Comment by way2muchnoise** [comment]
Intended behaviour, once that one is done it should do the next one.

**Comment by PapiDimmi** [comment]
Firstly, this is not a question.

Secondly, the disk manipulator only affects the topmost disk, like I said. It doesn’t move on to the other disks once it’s done.

I _assume_ that it only moves on to the next disks if the disks in the input slot are placed in the output slot, but that only happens if the disks are completely empty, which they aren’t in my case.

**Comment by way2muchnoise** [comment]
And you are sure that the items on the drive can be moved to your system?

**Comment by PapiDimmi** [comment]
Yes. Whenever I use the disk manipulator, I use it to move some items from my disks to my storage drawers, but unless the disks go in one of the output slots, which they only do if they’re completely empty, the disk manipulator doesn’t move on to the next disk.

**Comment by dovahkiin4991** [comment]
just get another disk you use when you are redumping items, that way it will empty as much of it into the drawers as possible and than any leftovers will just go to the new disk leaving you with an empty disk for next time you do this. Also making sure the priority is set to make sure everything possible will go to the drawers.

**Comment by raoulvdberge** [comment]
Intended behavior.
