### ISSUE TITLE
Refined Storage does not support crafting recipes that use tools that lose durability

### ISSUE THREAD

**Issue by PapiDimmi** [raoulvdberge/refinedstorage#1154]
Examples: Immersive Engineering’s hammer, Extra Utilities 2’s glass cutter, IndustrialCraft 2’s cutter, and so on.

When trying to craft things with these items, Refined Storage says that they’re missing, if they’re damaged.

This issue is slightly similar to #941.
****
**Minecraft version**: 1.10.2
**Refined Storage version**: 1.2.25
**Forge version**: 12.18.3.2272

**Comment by way2muchnoise** [comment]
Glass cutter and IC2 hammer should work as I have then in my testing environment. But I know the IE hammer had some issue which I did report to them on IRC.

**Comment by PapiDimmi** [comment]
>Glass cutter and IC2 hammer should work

It didn’t for me. It says that I am missing the appropriate tool, even though it’s in my system. I think it only works if the tool is not damaged, as I mentioned.

**Comment by way2muchnoise** [comment]
Did you try it with ore dict on?

**Comment by PapiDimmi** [comment]
No. I don’t see why that would affect anything, as the issue is, presumably, that it ignores NBT data.

But I will try that and see if it works anyway.

**Comment by PapiDimmi** [comment]
I just tried it, and it didn’t work.

I discovered something else as well: It does not work even if the tool, undamaged, is in the system. I tried to craft ender shards using an ender pearl and a glass cutter, but it says that I’m missing a glass cutter, even though I have an undamaged glass cutter in my Refined Storage system.

**Comment by BrianEdmonds** [comment]
Even for tools that don't lose durability, autocrafting can be a bit 
dodgy. With Mystical Agriculture in Sky Factory 3, you can upgrade to a 
crafting crystal (I forget the name now) that does not lose durability, 
but RS still requires you to have four of them to craft the top tier 
essences, even though there is no recipe that uses more than one.

**Comment by way2muchnoise** [comment]
The crystal is related to recursive crafting and thus isn't the same issue.

An other question would be how were the patterns created? JEI transfer or manual?

**Comment by PapiDimmi** [comment]
I did it with JEI, but I just tried doing it manually, and it worked!

I ran into another issue, though: I had a glass cutter that was almost broken, and when I autocrafted ender shards, Refined Storage changed its durability, and it suddenly had 249/250 durability for some reason.

**Comment by raoulvdberge** [comment]
@PapiDimmi Can you please stop with the fucking thumbs down emojis?

**Comment by PapiDimmi** [comment]
Why did you reopen this issue? I did solve my issue by manually creating a pattern, rather than using JEI. Did you reopen the issue because you’re going to fix that interaction with JEI?

>Can you please stop with the fucking thumbs down emojis?

What’s wrong with them? I’m reacting to comments by using emojis, similar to how I’d like comments on Twitter or YouTube; or upvote or downvote comments on Reddit. I don’t understand why such a trivial thing irritates you. The emojis are there to be used, aren’t they?

**Comment by Vahtera** [comment]
This issue is still/again present in FTB Sky Adventures at least, Refined Storage 1.6.8, Minecraft 1.12.2, IC2 2.8.101-ex112. Setting recipes for Oredict has no effect. Tried with clicking from JEI and making the recipe manually. Still trying to craft a Hammer or Clippers for each recipe (aka, only using non-damaged item). There is no button for ignoring NBT and/or metadata.

**Comment by madmacf** [comment]
Same problem with mekanism energy tablets i ATM3. Seems to be NBM related

**Comment by snydej** [comment]
This is still an issue. I'm trying to craft ender shards using the glass cutter from extra utilities 2 and it won't ever use a damaged glass cutter.

**Comment by weakman54** [comment]
Added in Refined Storage on Omnifactory (1.2.2), have the same issue with all the gregtech (CE) tools

**Comment by Cosmology2727** [comment]
I realized something terrible regarding this problem. Even if you can get it to recognize hammers and cutters (I'm doing IC2), it uses the ENTIRE tool for EVERY operation. I just wasted tons of stacks of iron because of this. It seems as though the Refined Storage system just looks to see what's needed, and when it crafts, it deletes the needed things from its inventory. That seems like a pretty lazy way to code it, but I can understand that being a lot easier to code than making each operation manually play out as if it's being legitimately crafted. Either way, it's definitely not working properly, and the crafting system is essentially useless when it comes to anything regarding tools.

**Comment by saikokami** [comment]
Problem still present in mceternal.
I don't think it will get fixed right?

**Comment by wiezba** [comment]
The problem is still here after 6 years lol
