### ISSUE TITLE
Grid items does not show up right away have to take out and re put in storage disk 1.11.2

### ISSUE THREAD

**Issue by general5001** [raoulvdberge/refinedstorage#1259]
#### Steps to reproduce:
1.
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:
- Forge:
- Refined Storage:

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Seems to also happen with external storage.

**Comment by general5001** [comment]
hope they will fix it in the next update

**Comment by 016Nojr** [comment]
Happens with me aswell on a server running the latest version (1.4.10)

**Comment by Squeegee** [comment]
I believe I am seeing something related.  Every so often, when I open a grid, there are a bunch of item locations with no icons and 0 quantity (like 10 rows of them in the extended UI).  Remove/replace the 64k drive fixes it.  Also had the same thing happen when I put in a new empty drive just after RS auto-crafted it.

One of the times I started (the first time that day), nothing was showing in the grid.  Opened and closed the grid several times with no change.  Removing/replacing drive fixed it.  When I went to the grid, none of the auto-crafting was available.  I broke and replaced a cable going to the block of crafters.  Opening the grid then was normal.

I can provide screenshot next time any of this happens if desired.

I am using version 28 of "The New Frontier" mod pack by ichigo_games.  There are two newer releases, but they require world reset (which I'm not willing to do yet).

Minecraft version 1.11.2, RS version 1.4.18, Forge version 2366, Java 1.8.0.111, x64, 10 GB memory allocated to java (out of 64 GB).

If there is anything else I can do to help, please feel free to let me know.

**Comment by raoulvdberge** [comment]
@Squeegee That would be issue #1233

This issue is fixed, though.
