### ISSUE TITLE
Storage Drawer API is out of date and can cause mod issues

### ISSUE THREAD

**Issue by xannor** [raoulvdberge/refinedstorage#1304]
This comes from an issue submitted to SD:
https://github.com/jaquadro/StorageDrawers/issues/492

I removed the SD api from my RS jar and so far everything is working normal.

RS: 1.4.14
MC: 1.11.2

**Comment by jaquadro** [comment]
I don't really know what's wrong, because AFAIK what RefinedStorage is doing with the API is fine.  But for some reason its version is getting picked as the definitive version in some cases, and it's out of date.

**Comment by raoulvdberge** [comment]
@jaquadro Can you please make it so that I can include the API with Gradle? That avoids issues as these.

**Comment by jaquadro** [comment]
Instead of including it in the jar task, could you try referencing them in sourceSets.api.java?  That's what I did for Thaumcraft/RefinedRelocation/Waila APIS -  https://github.com/jaquadro/StorageDrawers/blob/1.7.10/build.gradle#L40.  Just make sure any usage of the interfaces are completely gated behind a mod check.

If you're specifically looking for a Maven repo, I've never figured out how that's handled, though I guess CurseForge offers that for all hosted mods now?

**Comment by raoulvdberge** [comment]
Thanks, I will look into the source sets stuff.

Regarding hosting, I personally use a free service called Bintray. I auto-upload binaries to them (see my build.gradle) and the resulting jars are stored there.

From Bintray, you can then choose to make the API jar available for others, and they can include it in their mod then.

**Comment by raoulvdberge** [comment]
Fixed with Refined Storage 1.4.15.
