### ISSUE TITLE
Shift clicking in crafting grid is slow

### ISSUE THREAD

**Issue by Morpheus1101** [raoulvdberge/refinedstorage#1368]
#### Issue description:
When trying to craft for example the various tiers of Essence from MysticalAgriculture using the Crafting Grid, it has quite the delay from clicking on the item to make a stack to when it appears in the inventory, last count 6 seconds for it to appear in your inventory.

#### What you expected to happen:
When clicking on the item to produce the upgraded stack for it to be almost instant

#### Steps to reproduce:
1. Have a heap of Essence of of Tier 1-5
2. Have an Infusion or master Infusion Stone
3. Use JEI/NEI to follow recipe to make the Tier above the essence you have
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: *.2407
- Refined Storage: 1.5.10

Does this issue occur on a server? [yes/no]

Yes

**Comment by raoulvdberge** [comment]
Not sure what you're talking about, it's instant for me:

![x](https://raoulvdberge.com/7zljBD)

You're probably dealing with server lag.

**Comment by Morpheus1101** [comment]
Singly yes it is, but when shift clicking on the recipe so it does a stack at a time is where the lag occurs

**Comment by raoulvdberge** [comment]
That happens for every item, not just the essences.

**Comment by Quest79** [comment]
This is happening to me as well in. Using the Project Ozone Lite pack and wanted to use your mod instead. Issue has only been happening for the last few days and I finally figured it down to it being your mod and grid mods. Seems to be an issue with items in storage not loading well. It cuases MAJOR tick lag on the server for 5-10 sec on opening, and the same anytime anything is used. a single tick takes 50-150 ms during this time due to whatever the mod is doing to update the item array. I have not yet profiled, so im unsure if its a conflicting method or what.

Server itself is fine with 1-5 ms tick times when i am not using rs.

**Comment by raoulvdberge** [comment]
This has been fixed!
