### ISSUE TITLE
Can't Create Z-Logic Controller in EnderIO Slice'N'Splice

### ISSUE THREAD

**Issue by bcrotty** [raoulvdberge/refinedstorage#1396]
#### Issue description:
No matter how I set up the Z-Logic Controller pattern, the Crafter won't insert the items into the Slice'N'Splice. I'm using OreDict, and I've tried with and without the Axe and Shears that show up in the Output when you use JEI to create the recipe.

#### What happens:
The ingredients won't insert. On the Crafting Monitor it shows the ingredients under Items Inserting, and it shows the Z-Logic Controller as processing.

#### What you expected to happen:
The ingredients to insert into the Slice'N'Splice.

#### Steps to reproduce:
1. Create Z-Logic Controller pattern and put in Crafter facing Slice'N'Splice
2. Try to craft a Z-Logic Controller
3. Nothing happens
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2316
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no] Unknown

**Comment by raoulvdberge** [comment]
This is most likely an Ender IO issue, RS only interacts with the inventory. Are you inserting at the right side?

Either way, 1.10.2 is unsupported.

**Comment by Tahakk** [comment]
In my world I'm creating every controller using crafter from RS without problem.

1. Do not include axe and shears into recipe -> leave them inside Slice'N'Splice
2. Do not use oredict, because that can lead into inserting wrong head/skull for wanted recipe and Slice'N'Splice then block slots until it get right items which are supposed to be inserted with given head/skull

**Comment by bcrotty** [comment]
That did it for me. Thanks @Tahakk ! I'd been working around it with a chest, but this is much better.
