### ISSUE TITLE
Capacity display on external storage is wrong

### ISSUE THREAD

**Issue by llloyd4** [raoulvdberge/refinedstorage#1409]
#### Issue description:

The capacity showing on an external storage bus on a Yabba barrel shows oddness, something like 254 / 64 at 300 ish %.

#### What happens:

The External Storage bus shows impossible numbers

#### What you expected to happen:

To see the correct capacity of the barrel.

#### Steps to reproduce:
1. Place down Yabba barrel
2. Place more than a stack of stuff in the barrel
3. Place an External Storage bus on the barrel
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12
- Forge: 1.12-14.21.1.2443
- Refined Storage: 1.5.14

Does this issue occur on a server? [yes/no]

No idea, playing in single player

#### If a (crash)log is relevant for this issue, link it here:

http://i15.photobucket.com/albums/a395/llloyd4/2017-08-08_01.12.37_zpsflmjtzax.png

https://github.com/LatvianModder/YABBA/issues/35

(In case your wondering, have had compatibility issues boil down to both mods authors blamed the other mod author so...  )

**Comment by KumaSamaVII** [comment]
I am having the same issue with storage drawers

**Comment by MrDoboz** [comment]
I have the same with Storage Drawers, especially the compacting drawers. I have it 54200% full. This is not just an asthetic problem, because the system doesn't even try to export the incoming items into the drawers, so the disks are filled with ingots and stuff in minutes. I don't expect a real fix soon, as it would be really difficult to calculate the actual capacity of a set of compacting drawers. Especially with a void upgrade (that should mean infinite capacity from the rs system's point of view). What about a quick fix of adding a button to ignore capacity and just try to export the things anyways? I mean it works for exporters, but I can't whitelist all the items in one exporter (maybe an exporter with like 10 rows?). One more big plus would be a button to automatically export everything from the disks, so I don't have to set up a bunch of exporters every time I build some drawers for items I have a shitton of. Hope you consider these options as this is kinda a game breaking bug. Kills the fun.

**Comment by Darkere** [comment]
The capacity display is purely visual. It has NOTHING to do with being able to insert or extract items into the inventory.

**Comment by MrDoboz** [comment]
Oh cool then, but in that case, why did 60K iron ingots fill my disks, when the disk drive was set to priority 1, and the external storage to the drawer controller literally to 20000? (and no, it didn't work with a more reasonable priority either) I mean I read that in the official guide that the system puts the item in the highest priority storage, IF IT'S NOT FULL. So I tought the code to determine if it's full or not might be broken if the display is off too. so any ideas? Btw now it's working with 6 exporters constantly pumping the items into the drawers, the external storage by itself does not put anything in there by itself (no, it's not set to extract only).

**Comment by Darkere** [comment]
Did you modify the whitelist/blacklist button maybe?

**Comment by MrDoboz** [comment]
No, I did not. Actually it's kinda crap now again. Sometimes the resources don't show up in the grid, and I have to turn off and on the external storage for it to work again. Sometimes it works without the exporters btw, but not often enough that it wouldn't fill my disks. It's pretty unstable to be honest. I don't know what it actually takes to reproduce the bug, but I can upload my world somewhere if you would like to take a look at it

**Comment by llloyd4** [comment]
@MrDoboz Are you using Forge Chunk Loading? If so that is the cause of the External Storage disconnects until broken / replaced. I fixed that by installing and using Chicken Chunks, it's something to do with how broken Forge chunk loading is.

**Comment by MrDoboz** [comment]
I don't know, I'm playing on Feed the Beast Revelation. There is FTB utilities in that, and I use that for chunk loading. Maybe that is using forge chunk loading? I will try chicken chunks then and see if it fixes the problem. Thanks!

**Comment by simonrydder** [comment]
I'm having the same problem with 500% full Drawer Controller. Items are going into the system correctly but every time the server starts the system can't see the external storages. Have to break and replace it every time.

**Comment by Darkere** [comment]
The you are looking for #2120
