### ISSUE TITLE
Massive TPS Drops

### ISSUE THREAD

**Issue by mrkirby153** [raoulvdberge/refinedstorage#1525]
#### Issue description:
The server TPS drops significantly after server startup and eventually degrades until it is unplayable.

#### What happens:
After the server being online for 4 or 5 hours (not really sure, just an estimate), the TPS on the server drops from 20 down to 15-16, noticeably slowing down the game. The cause of the lag appears to be an RS system with over 10 million items stored in a Quantum Storage Disk.

#### What you expected to happen:
The server continues to run at 20 TPS and no performance drops occur
#### Steps to reproduce:
_This issue is kinda specific to one server, but there may be an underlying cause_
1. On the server, there is an RS system with over 10 million items in it. Powering up the RS system or leaving it running for an extended period of time appears to tank the TPS
2. Power off the RS system, and observe the TPS return to normal
3. Turn back on the RS system and the TPS drops again after the network has stabilized.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.0.2517
- Refined Storage: 1.5.21
- Modpack: All The Mods 3 v4.4

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant to this issue, link it here:
[TickProfiler thread dump](https://gist.github.com/mrkirby153/25b1b1ecb1d43aaa07dc1f00f9b66ad3)

[Profiling Results](https://github.com/raoulvdberge/refinedstorage/files/1456491/Profiling.Results.zip) collected following instructions from [here](https://refinedstorage.raoulvdberge.com/wiki/profiling)

**Comment by raoulvdberge** [comment]
That is because an Interface block is exposing the network inventory, and that is being slow.

**Comment by mrkirby153** [comment]
Is there anything that can fix this?

**Comment by raoulvdberge** [comment]
Removing the Interface block in question or configuring a export/import config on the Interface should help.

**Comment by andr9528** [comment]
I seem to have similar problem, with my TPS dropping like crazy when the Refined Storage system is online, i go down to like 0,75 TPS, which make me unable to do much at all. Breaking the Cryotheum Duct to the controller take roughly 2 minutes to registre.

I have already made sure all my interfaces are configured with something, even those that are only supposed to import into the system, those have gotten a single torch to keep stocked.

My system has acces to 2 large Storage Drawer arrays, which holds a large quantity of items, (> 6 Mil < 12 Mil) on top of that it has two Reborn storage disks (max sized disks) which are 1% full (around 0.55 Mil items)

[RefinedStorageLag.zip](https://github.com/raoulvdberge/refinedstorage/files/1646865/RefinedStorageLag.zip)

In the file above i have included the Sampler .nps file, and the stall-reports folder that sampler also generated, hope theses help narrow down the cause.

Versions:
StorageDrawers-1.12.1-5.3.3
refinedstorage-1.5.31
Minecraft 1.12.2
forge-14.23.1.2590
RebornStorage-1.12.2-3.0.3.36
RebornCore-1.12.2-3.6.2.187-universal

I updated my mods yesterday, before that i didn't feel this amount of lag, so i also tried to downgrade to version 1.5.28 of refined storage to see if the issue was present in that version too, if not that should narrow the cause down to something recently added/changed. 
After testing the lower version i can say that it also had the issue, i might just have hit the amount of items today to trigger this issue, the older version does seem to take longer before actually accepting power from the duct when placed (took almost 4 min befor the controller lit up, whereas in the newer version it lights up almost instantly).

Hope the issue is found and fixed soon, would really like to continue playing on this map :)

**Comment by andr9528** [comment]
Upon further testing i have determined that my lag is coming from my diskdrive when it has my 2 16384K storage disks (From Reborn Storage) in it, so the issue might be on their side of things.

Will file a issue over at them with a link to this issue.

**Comment by andr9528** [comment]
On even more testing it seems that any disk in the disk drive drops the TPS, regardless of whether or not the disk contains a lot of items, so it might not directly be the reason of drive, but rather the rate of insertion of items, altho larger disk do drop more TPS.

**Comment by andr9528** [comment]
Stopping any form of insertion to the drives does lower the amount of TPS drop that they give off, by 50-70%, but the TPS is still low to a point of unplayable...

Might simply be a matter of system size, with many interfaces requesting certain items from the drives, even tho most of the items they request in my world are stored in the storage drawers...

Making a simple Drive-Grid-Controller system and putting in any disk has no effect on the TPS, so a possible solution could be to allow External Storage to connect 2 different (via a interface) systems together with out them becoming one system, that one all the items could be stored in a small system, with as few blocks in the system. Another solution could simply be to not allow interfaces and external storage to connect system wise but only item wise.

**Comment by raoulvdberge** [comment]
Can you make a nps file based on your findings of the insertion lag?

**Comment by andr9528** [comment]
Sure here it is. the sampler ran while i collected the TPS reading below, i did the tps reading in the order that it is written down, so that you can follow it through the sampler data.

[RefinedStorageLagNr2.zip](https://github.com/raoulvdberge/refinedstorage/files/1649176/RefinedStorageLagNr2.zip)

TPS reading with no drives in disk drive: 30-40 ms - tps 20
TPS reading with drive containing 0,58 Mil items in disk drive: 1600-2100 ms - 0,45-0,6 tps
TPS reading with empty drive in disk drive: 40-300 ms - 6-20 tps
   --- Emptied drive to get down and start the importing.
TPS reading with drive containing 0,58 Mil items in disk drive & inserting items: 2000-2100 ms - 0,45-0,5 tps
TPS reading with empty drive in disk drive & inserting items: 450-600 ms - 1,8-2,1 tps
   --- Game did a backup while this disk where in.
   --- Removed the disk before stopping the sampler.

All test was done with my 16384K drives.

So after the test i can see that 50-70% was a bit of a stretch, but insertion did effect how low/high it went.

I have also included my stall reports onces again, which have grown in amount, from my all my testing today.

**Comment by psykoe** [comment]
I have just found an issue that's kinda similar I guess.

I made a max size 10x10x10 Colossal Chest and hooked it to an external storage and it dropped the TPS of the server to something like 7 I believe it was. This is in All The Mods 3 with mod versions:


All The Mods pack version 5.8
Colossal Chests 1.6.8
Refined Storage 1.5.31

Please let me know if there's anymore information needed, quite new to posting here.

**Comment by raoulvdberge** [comment]
The fix is simple: don't connect an external storage to a collosal chest. I think it's obvious that RS can't handle bookkeeping of that many slots.

**Comment by psykoe** [comment]
Oh i'm sorry I must have missed that somewhere.....No need to be rude about it. I have seen a 11x11x11 used on a AE system with no issues before so I assumed RS could do the same. I was wrong and thought I would report the issue of it destroying TPS. Disregard then.

**Comment by raoulvdberge** [comment]
RS no longer has the interface exposing inventory feature because this issue, so this can be closed.
