### ISSUE TITLE
Processing + OreDict recipes in special case won't work

### ISSUE THREAD

**Issue by roboderpy** [raoulvdberge/refinedstorage#1553]
#### Issue description:
It seems Processing recipes work weird with oreDict enabled, and not working if there is two items with same ore dict in system

#### Steps to reproduce:
1. Create a pattern like this one - ![recipe](https://i.dbot.serealia.ca/2017/11/cea40d1e64_javaw_2017-11-26_16-51-22.png)
2. Put **exact** amount of needed obsidian dust of **item type which was defined** in pattern
3. Put one obsidian dust from other mod
4. Put pattern into crafter next to chest (for test)
5. Attempt to autocraft
6. Nothing happens, chest is empty, crafting monitor displays Machine is in use. Removing other's mod obsidian dust from storage system instantly makes autocrafting work.

#### Version:

- Minecraft: 1.12.2
- Forge: 2538
- Refined Storage: 1.5.22

Does this issue occur on a server? [yes/no] yes

**Comment by Paril** [comment]
You're trying to use the Mekanism machine, yeah? Does it even accept other mods' dusts for infusing? If not, then this is working as intended technically since you told it it can send any type of dust to it. I have the Metallurgic Infusers set up to use the dust that it asks for in the recipe (if you use JEI/NEI, you can use the + button to send the ingredients right to the Pattern Grid) and it works fine.

**Comment by roboderpy** [comment]
Raoul already replicated this bug

**Comment by Paril** [comment]
Oh I see, I misread the bug, I thought it was attached to the machine or something. I was having a similar issue where it would send nothing at all sometimes for that same recipe, I got around it by using exporters to just fill my infusers up with redstone/refined obsidian/diamond respectively so they were always prepped.

**Comment by raoulvdberge** [comment]
Processing recipes will no longer have oredict mode
