### ISSUE TITLE
Autocrafting Server closed

### ISSUE THREAD

**Issue by ejjo01** [raoulvdberge/refinedstorage#1567]
#### Issue description:
I know my english is bad
if i in a autocrafting prozzess, Server closed
#### What happens:
i have an interface with 2 item for Export. on the top is an external storage (export only) in the interface is a crafting upgrade. the 2 item are yellow petal and tall yellow flower. i want to stack 16 in the system. if i take  the 16 out the system. the crafting prozess are starting and the server closed.
#### Steps to reproduce:
1. 
2.
3.
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:14.23.0.2544
- Refined Storage:1.5.25
- refinedstorageaddons: 0.2

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:
https://pastebin.com/yAxagggs

**Comment by Chasewhip8** [comment]
Accoutering in MC 1.10.2 as well. No fix found. 

[crash-2017-12-10_04.55.33-server.txt](https://github.com/raoulvdberge/refinedstorage/files/1545307/crash-2017-12-10_04.55.33-server.txt)

**Comment by MineMaarten** [comment]
Got this in the DW20 pack as well:

https://pastebin.com/sgpKVS6a

I can explain a bit what happened in my case, it might be helpful:
1. I had just added a recipe: 1 bone -> 6 bone meal with a crafter + importer on a TE Pulverizer (crafter was existing already for other recipes).
2. I let the autocrafting create craft 36 items involving the bone meal.
3. It only crafted 32 items, and basically was stuck on the last set to craft.
4. After investigation, it seemed the autocrafting went crazy, and kept adding bones one by one in the pulverizer, and I had plenty bone meal to do the last craft.
5. I canceled the autocrafting operation.
6. I restarted the autocrafting operation for the last 4 items, expecting not having to do any processing steps. This is when it crashed.

It might be related to the crash, because the autocrafting definately behaved weirdly, not crafting the last set in step 3 and 4.

//Update
After restarting, and seeing if I could reproduce it:
7. Tried to restart the crafting operation, got the following, which I'm sure I did not get before:
![image](https://user-images.githubusercontent.com/5345405/34465047-c4acd7ec-ee9c-11e7-923c-25c9a9c4315c.png)
8. There shouldn't be any circular dependencies, for dyes I only have the following recipe:
cactus green + bone meal = lime dye (Ore dict support enabled)
And the recipe I was trying to craft:
![image](https://user-images.githubusercontent.com/5345405/34465053-1d4a69e6-ee9d-11e7-80df-57b0a1a7cda6.png)
9. I was suspecting something with ore dict, so I tried disabling the ore dict support on the recipe from the screenshot. This worked, no circular dependency.
10. The recipe still didn't craft, but that was because there was only 1 cactus green left and I didn't set up a recipe for that yet (which would explain why only 32 of the 36 items could be crafted in step 3).

It feels to me like ore dictionary handling might be the cause of this, maybe the fact that dyes are 'dyeGreen', but also in a generic 'dye' section. Could it be that the autocrafting incorrectly detects a circular dependency because of that (as I have a dyeGreen + dyeWhite = dyeLime recipe as well)?

Let me know if you need more info.

**Comment by TMarc** [comment]
I have the same issue on the same craft
I have removed the option "oredict" and it solve the issue. 

It's a workaround but seems a bug with oredict.

**Comment by MineMaarten** [comment]
> PS: Disable "processing" it's not a craft in a machine
Uhh yeah, that's a screenshot derp, it definately was not configured as a processing recipe.

**Comment by raoulvdberge** [comment]
@MineMaarten 

The circular dependency checking basically checks if a same pattern is used multiple times.

Can you retry with the latest version? The circular dependency message will display the offending pattern as well.

Regarding your crash, it seems unrelated to the circular dependency problem.

**Comment by MineMaarten** [comment]
Okay good news, I've isolated the problem for you in a test world with just refined storage latest (refinedstorage-1.5.31.jar), and a clean refined storage system.

Steps to reproduce:
1. Set up a crafter with the following two recipes (used for vanilla crafting)
Recipe 1: green dye + white dye = lime dye (uses Ore Dict enabled)
Recipe 2: 1 bone = 3 bone meal (uses Ore Dict enabled)
![2018-01-01_22 09 48](https://user-images.githubusercontent.com/5345405/34471138-ae8fa756-ef40-11e7-8dfe-5c3adac65164.png)
2. Set up the items in storage as the following:
![2018-01-01_22 10 11](https://user-images.githubusercontent.com/5345405/34471147-f02574e8-ef40-11e7-8ed4-0c67c743cb75.png)
Items in storage: bones, bone meal.
3. Try to craft lime dye. This fails with a circular dependency error (might be correct, as it might be seeing dye + dye = dye (whatever dye that might be)).
![2018-01-01_22 10 14](https://user-images.githubusercontent.com/5345405/34471150-2ce040b6-ef41-11e7-9ee6-6c3c5f4eba56.png)
4. Now remove the bone meal (so only bone is left).
![2018-01-01_22 10 19](https://user-images.githubusercontent.com/5345405/34471151-3918800a-ef41-11e7-95a9-98968312117b.png)
5. Try craft lime dye. This is now allowed:
![2018-01-01_22 10 23](https://user-images.githubusercontent.com/5345405/34471153-43fe9f86-ef41-11e7-8884-82cd21d2fe90.png)
6. If you press 'Start', it will go mad on crafting bonemeal, and after a few seconds the game will crash with the crash log I posted.

**Comment by raoulvdberge** [comment]
Thanks - I will take a closer look tomorrow.

**Comment by hunter688** [comment]
Any progress ?

**Comment by Blackcatz1911** [comment]
https://pastebin.com/pYUD6FKg
Still having this problem in 1.5.31
Crashlog: https://pastebin.com/pYUD6FKg
