### ISSUE TITLE
Fluid Disk Manipulator terribly unbalanced

### ISSUE THREAD

**Issue by ineternet** [raoulvdberge/refinedstorage#1650]
#### Issue description:
The Disk Manipulator in Fluid mode works slowly (1 Item = 1 mb).

#### What happens:
A Disk Manipulator in Item mode without any upgrades extracts about 1 Item per second. Fluid disks are treated same same, handling 1 mB of fluid per second.

#### What you expected to happen:
Something more balanced. Fluid Disks have a maximum capacity of 64k, while Item disks have a capacity of 1k. A Fluid Disk should extract 64 times as fast (or some other number) to make it not *horribly* slow (even with four speed upgrades).

#### Steps to reproduce:
1. Put a Disk Manipulator in fluid more.
2. Insert a Fluid disk, make it work.
3. Watch the transfer rate.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.1.2577
- Refined Storage: 1.5.32

#### Demonstration Video:
https://gfycat.com/CheapMajorIchthyostega

**Comment by Saklad5** [comment]
Usually “unbalanced” means it is overpowered, but I suppose it’s technically correct here. I honestly think all of the fluid storage is way too small for the cost. I tend to only keep one Fluid Storage Disk for miscellaneous fluids and just keep a room of Demonically Gargantuan Drums with External Storages attached for each liquid I want to store.

I feel that 1000mb should scale the same way one item does, since that’s how that amount of fluid would be stored as an item.

**Comment by raoulvdberge** [comment]
1 mb is indeed very slow. I'm going to increase it to 1000 mb, analog to the item rate.

Stack upgrade will give 64 000 mb /t.
