### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by HenryLoenwind** [raoulvdberge/refinedstorage#1682]
#### What happens:

```
java.lang.NullPointerException: Ticking block entity
	at java.util.ArrayList.removeIf(ArrayList.java:1411)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.CraftingTask.update(CraftingTask.java:513)
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.CraftingManager.update(CraftingManager.java:181)
	at com.raoulvdberge.refinedstorage.tile.TileController.func_73660_a(TileController.java:204)
```

#### Steps to reproduce:
see user comment below

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.2.2615
- Refined Storage: 1.5.31

Does this issue occur on a server? yes

#### If a (crash)log is relevant for this issue, link it here:

https://server.enderio.com/crash-reports/crash-2018-02-20_16.37.22-server.txt

https://server.enderio.com/crash-reports/crash-2018-02-20_16.49.55-server.txt

**Comment by temp1011** [comment]
Hi I'm the user who keeps causing this. I'm essentially autocrafting essence for mystical agriculture using the phytogenic insolator from TE. It is a bit of a weird setup. Here are the things that I think make it different from normal:
![2018-02-20_15 53 38](https://user-images.githubusercontent.com/34900092/36434435-ead9bcbe-1656-11e8-81c2-3d87e21d77ca.png)
Pattern has product on other side since seeds are needed (maybe some recursion weirdness?)
Crafting jobs are quite large (maybe 50 lots of seed, could be up to 1000 essence)
![2018-02-20_16 01 47](https://user-images.githubusercontent.com/34900092/36434631-620f4222-1657-11e8-8b39-0a6ab8ebf661.png)
3 Crafters on 1 machine and thermal mediator (block from thermal expansion that speeds up adjacent TE machines). I don't think this should be an issue since it's not ticking the network as well but that could be the problem.

I'm happy to provide any other information about the setup if needed.

**Comment by temp1011** [comment]
I'm going to go and test the thermal mediator now to see if it's causing issues, I'll report back if it does.

**Comment by raoulvdberge** [comment]
It would be really great if the duplicate bug reports would stop.

#1629

**Comment by raoulvdberge** [comment]
The comments posted here will be considered when fixing this bug as it's been tagged as duplicate.

**Comment by HenryLoenwind** [comment]
that crash isn't even near the other one...

**Comment by raoulvdberge** [comment]
Sorry, meant #1567.

**Comment by HenryLoenwind** [comment]
That's why I like having the actual crash in the ticket text, so you have a chance to find existing crashes without having to read 120 tickets back... ;)

https://github.com/raoulvdberge/refinedstorage/search?q=java.util.ArrayList.removeIf&type=Issues&utf8=%E2%9C%93

**Comment by raoulvdberge** [comment]
Yeah sorry I might have reacted too harsh, but I am tired and I've seen this particular stack trace so much already on this tracker.

**Comment by HenryLoenwind** [comment]
Then go to bed early and put a try-catch block around that point tomorrow until you fixed the underlying issue ;)

**Comment by raoulvdberge** [comment]
I don't like masking issues like that ;)

**Comment by HenryLoenwind** [comment]
I'm sure people don't like their servers crashing either...

I don't really mind, but that's because I crash our test server all the time anyway, so it doesn't matter ;)
