### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by MCPhilippS** [raoulvdberge/refinedstorage#1726]
Hello, I am posting this here because after reading a few of your twitter posts, this seemed to be the least wrong place to do so. I really like your mod, the way everything works out as expected is wonderful! I particularly like the storage blocks with the build in overflow void function.
Still there are a few minor things that I miss, like cable covers for example. 
But what I'm here for to say is that I always wanted a funtion with which one can keep a certain amount of a specific Item (/fluid) at all times in the system, because it feels like every time a recipe needs something like a piston, you do'nt have one on stock so you have to click your fingers off just because you where missing this one step of crafting, you may know what I mean. 
Maybe like an "advanced detector" that detects the amound of an set Item and triggers the autocrafting after an adjusted amount of time (so that it does'nt immediately starts crafting new Items if you take them out to put them in the crafting grid by hand).
I would love it if you could do some programming magic and make that a thing.
Have a nice day Sir!
(edit: I'm sorry if there are any mistakes, I'm not a native speaker of english)

**Comment by Saklad5** [comment]
You can use Detectors to do that with Exporters and Interfaces, but I would like a cleaner way to do it. If you want to use OpenComputers with [this program](https://oc.cil.li/index.php?/topic/1408-refined-storage-autocraft/) to accomplish it. If you want a delayed response, I’m sure you could modify it to do that too.

Since on-demand fluid crafting doesn’t actually exist right now, your best bet is to use a Detector and an Exporter with a fluid producing system (Magma Crucible, etc.).

**Comment by MCPhilippS** [comment]
That helps a lot, I will try it out. Thank you very much :)

**Comment by Saklad5** [comment]
Oh, and my debatably useful advice is to program literally everything you ever want to craft into Patterns, aside from one-time things like upgrading an item. This is probably harder without Reborn Storage, but it saves me the trouble of having to do manual crafting requests more than once.

**Comment by raoulvdberge** [comment]
You can do it without exporters and detectors. Check the wiki.
