### ISSUE TITLE
[1.10.2] Server crash when autocrafting while chunk unloads

### ISSUE THREAD

**Issue by Keridos** [raoulvdberge/refinedstorage#1765]
#### Issue description:
Server crash when autocrafting while chunk unloads
#### What happens:
Server crashes
#### What you expected to happen:
Server not crashing
#### Steps to reproduce:
1. Start crafting job
2. walk away from it so the chunk unloads
3. server crashes

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.3.2511
- Refined Storage: 1.2.26

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

https://paste.ee/p/fmwdj

##### Some more info:
https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/com/raoulvdberge/refinedstorage/apiimpl/autocrafting/task/CraftingStep.java#L184-L185

Seems like on your preliminarySteps List there is at least one entry that is null.

**Comment by raoulvdberge** [comment]
- https://refinedstorage.raoulvdberge.com/community ("We won't accept bug reports for Minecraft 1.10.2.")
- Look through to the 403 "invalid" bugreports on the issue tracker.
- The last RS 1.10 release is from 10 June 2017. That is almost a year.

I'm not going to repeat myself to death with "1.10 is unsupported" with all these obvious factors listed above because you don't want to do any research.
