### ISSUE TITLE
Autocraft - Recipes with more than one output item

### ISSUE THREAD

**Issue by wandersonbrazdf** [raoulvdberge/refinedstorage#1890]
Hi friends, I have a problem with the autocraft of Refined Storage, I made the pattern of the binder composite of the ender IO it has an output of 8 items per recipe, when I command to craft 2 only I receive 8 instead of 16 that would be correct , for example I did a small video showing the problem.
...
1 - Create a Binder Composite pattern
2 - insert in crafter
3 - Craft in the system

video showing the occurrence https://youtu.be/3afoifOXwao

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.3.2655
- Refined Storage: 1.5.34

Does this issue occur on a server? [yes/no]
no

**Comment by imerr** [comment]
This seems to be the intended result

You're asking it to craft 2 items, not execute that specific craft twice. And since the minimum it can make is 8 you're getting 8 (it can't only craft a quarter)

**Comment by wandersonbrazdf** [comment]
I do not want to create only 2 but 16 if each recipe of 8 if I ask for 2 recipes would have to have an output of 16 in the end.

**Comment by imerr** [comment]
The crafting amount is not how often to craft the recipe though, it's how many items it should craft

If you want 16 items, you'll need to ask it to craft 16 items

**Comment by wandersonbrazdf** [comment]
@imerr I understood this part for example if I want 64 glasses I order 64 but the problem is that there are recipes that do not give 1 but several output items have a way to make the system understand this...

**Comment by imerr** [comment]
The system does understand this just fine though.
Take paper as an example:
You need 3 sugar canes to make 3 paper.

If you request 1 paper from the system, and there is non in storage (and it has the recipe, of course) it will have to craft some.
In order to craft 1 paper, it has to use the recipe "3 sugar canes = 3 paper". So there will be 2 extra paper the system has to create to fulfill your request of one paper

If you request 2 paper (as in 2 items of paper), it will do the same, but only have 1 extra paper.
If you request 3 paper, there will be no paper left over.
If you request 4 paper, it will have to run the craft twice, resulting in 6 paper, 2 extra.

The craft menu is not "run this crafting recipe X times", but "get me X amount of this item"
