### ISSUE TITLE
Immersive Engineering Hammer/Wire Cutters Issue

### ISSUE THREAD

**Issue by rhpeZ** [raoulvdberge/refinedstorage#1961]
When trying to cut wires or hammer down ingots using the autocrafting system, instead of using a Hammer or pair of Wire Cutters that are already in the system it creates a new tool each time.

I have tried to use oredictionary and tried without and the bug still persists. I have tried removing the pattern to create a hammer or wire cutters but it says that they are missing and will not let me craft the items.
#### Steps to reproduce:
1. Have pattern to create plate or wire in system.
2. Request craft of either.

Version
- Minecraft: 1.12.2
- Forge: 14.23.4.2739
- Refined Storage: 1.6.3

Does this issue occur on a server? Yes

https://gyazo.com/da856d72a674f3596e2e60035fbef9df (Hammer's in the system)
https://gyazo.com/0e568a781ed42d9d6695faa0a731bcff (System requesting to craft more)

**Comment by GioSerpo** [comment]
Just to point out, this issue isn't just for the IE tools. It's pretty much any tool that does the same thing, from any mod, even itself, as pointed out in #1965 

I literally can't auto craft the processors that are required to build the other items I need, because of this issue, and it's mod-breaking, because the biggest focuses of this mod are network based mass storage, and auto crafting with a system similar to AE1. If the auto crafting breaks on internal, required items, then that essentially says "oh look, a key selling point is messed up, let's find something else." If this isn't already a high priority, it needs to be.

**Comment by raoulvdberge** [comment]
The autocrafting still works, it just makes too much. So this isn't mod breaking and processors can be crafted just fine.

**Comment by GioSerpo** [comment]
I'm assuming that the issue i have differs a little bit then, as it tells me it has the cutter, it also says it needs a cutter, but, even with the pattern in a crafter, it won't make the cutter... However, even if it did, I don't want my storage system cluttered with that many items, but i could look over that issue if it would make my processors...

**Comment by fael13** [comment]
I have the same problem as @rhpeZ.
Playing on direwolf20 1.12 pack

Version:
Minecraft: 1.12.2
Forge: 14.23.4.2738
Refined Storage: 1.6

**Comment by eihns** [comment]
Ive noticed the same, but it the tool for creating the things for refined storage e.g. it created like 20 of them, but it uses them eventually and only crafting new ones when you request more items then you ever did before.

**Comment by raoulvdberge** [comment]
The crafter no longer handles reusable items. You'll need an external mod to do this (e.g. RFTools crafter). A RS-based solution might come in the future.
