### ISSUE TITLE
Suggestion: Crafting Monitor changes color when crafting process is stopped.

### ISSUE THREAD

**Issue by PourBrough** [raoulvdberge/refinedstorage#197]
There's really no way to to be notified if your crafting processes have stopped because of missing items or other issues. If it does halt for any reason, the Crafting Monitor should emit a red screen instead of blue, or emit a beeping sound, or both.

**Comment by raoulvdberge** [comment]
No, I don't think that is neccesary.

**Comment by raoulvdberge** [comment]
I've once again changed my mind on this. Since I'm planning to add a Wireless Crafting Monitor, it should
be easier to see when tasks are blocked.

Also, if I ever add a color changing mechanic to the Crafting Monitor, I should also add it to the Wireless Crafting Monitor for consisteny, and thats a load of work which I can't justify for such a small feature.

**Comment by BrianEdmonds** [comment]
@raoulvdberge Would you mind if someone else implemented it? That is, are you actively opposed to it, or just not interested in doing it? I think it would be handy to have some sort of status indicator on the crafting monitor. I'm not volunteering (yet), since I have zero experience writing Minecraft mods, but it's something I'm considering getting involved in, and I do have years of software engineering experience in general.

**Comment by raoulvdberge** [comment]
I'm opposed to it because I don't think it's needed in RS. So, if anyone would PR this I'd reject the PR.
