### ISSUE TITLE
Show Storage Disks that are in the Disk Drive on the block texture

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#21]

**Comment by WhiteFire-Sondergaard** [comment]
Possible alternative: unlike AE2 where individual drive status (stacks full, drive full) is important, drives in this mod mostly use their disks to expand storage. So instead of a drive by drive report it might be nice to have the overall drive status reflected like the energy bar on the controller.

**Comment by raoulvdberge** [comment]
that is a wonderful idea actually, will pass this to gusto.

**Comment by raoulvdberge** [comment]
Done
