### ISSUE TITLE
Autocraft can't detect buckets of liquid w/oredict

### ISSUE THREAD

**Issue by Thepenguin9** [raoulvdberge/refinedstorage#2165]
#### Issue description:
When attempting to autocraft with a bucket of liquid in oredict mode, the system can't see it

#### What happens:
If you have the preceding crafting steps setup, or even having the correct liquid bucket in the system, the system cannot see any buckets at all when crafting. The example I have is signalum production

#### What you expected to happen:
The system would melt the redstone, move that into a bucket, then use the bucket along with 3 copper dust and 1 silver dust to create signalum

#### Steps to reproduce:
1. Have a pattern setup to create a bucket of destabilised redstone, or have one already in the system
2. Create a crafting pattern in oredict mode to create signalum blend
3. Ask the system to make any amount of signalum blend
4. System will not see the bucket, nor a recipe for it if the patterns are in oredict mode

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2807
- Refined Storage: 1.6.12

#### Does this issue occur on a server? 
Yes

#### If a (crash)log is relevant for this issue, link it here:

N/A

**Comment by Thepenguin9** [comment]
As an added note this seems to happen with similar patterns, such as the flux capacitor, Mekanism's energy tablet and solar panel etc

**Comment by Vahtera** [comment]
> As an added note this seems to happen with similar patterns, such as the flux capacitor, Mekanism's energy tablet and solar panel etc

Mek's energy tablets have always been wonky, they haven't worked for me ever, not in ore-dict mode, not without it. There's some code with those that just doesn't agree with anything.

That signalum-creation has definitely worked in earlier versions, I'm curious to why it happens. Have you tried using the liquid-crafting system? Can it make the signalum blend recipe if you have destabilized redstone in the network and make a fluid-crafting recipe for it?

**Comment by Darkere** [comment]
These are 2 different Issues Please keep them separate. 

The Oredict button on the latest version is broken. It has worked before and is broken in a very fundamental way that I expect the fix is not too difficult. It should get fixed as soon as (and if) Raoul comes back to work on the mod. 

Mekanism machines and energy tablets have additional NBT data that is applied to them once they are crafted. This data cannot be read from the recipe and thus is not there when you import the recipe via JEI. You can insert an already crafted Item into the recipe to get it working. 

Since pretty much everything around the issue is changing in 1.13, we will have to live with it for now.

**Comment by Thepenguin9** [comment]
> These are 2 different Issues Please keep them separate.
A different issue with a similar root cause, I figured it would be better to include it

>Since pretty much everything around the issue is changing in 1.13, we will have to live with it for now.

Do you have a link to a roadmap or similar?

**Comment by Darkere** [comment]
No there is nothing of the sort. This is just me knowing what changes in 1.13 and hoping for the best :).
