### ISSUE TITLE
Filter not working in exporters

### ISSUE THREAD

**Issue by Kondensatorr** [raoulvdberge/refinedstorage#2177]
#### Issue description:
Putting filter with item list inside exporter doesn't filter items(it doesn't work at all). I guess this functionality was removed(???) because of this in changelog: "You can no longer put a Filter in filter slots to gain additional filter slots (raoulvdberge)" but I the thing is I can put it there but it doesn't work so I don't know if it is intended or not.

#### What happens: 
Filter doesn't filter items in exporter

#### What you expected to happen:
 Filter filters items in exporter. If filter functionality is as it should be then i suggest adding item that would let me and other players of big modpacks to put more than 9 items in eg. ore processing.

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.9

**Comment by Andronomos** [comment]
I was ecstatic to discover the filter because I thought it worked in any Refined Storage item that had filter slots. I was extremely disappointed to discover it only worked in a grid (who really needs that anyway?).

This needs to be a feature. The exporter/importer are practically useless any decent sized set-ups due to their limit slots.

In my mob farm, I need anywhere from 10 to 60+ different items going into a single block (LootBags Recycler, Uncrafting Grinder, etc..). Sure, I could use another mod but none of them are as quick as refined storage with speed and stack upgrades (I need to moved hundreds of items every few seconds).

**Comment by raoulvdberge** [comment]
It has been removed, no need to make new issues regarding this.

> but I the thing is I can put it there but it doesn't work so I don't know if it is intended or not.

If you now put it there you're just filtering for literal filters.
