### ISSUE TITLE
Game wont start, some COFH/API classes are not found [refinedstorage-0.8.12.jar]

### ISSUE THREAD

**Issue by PrinceOfAmber** [raoulvdberge/refinedstorage#222]
Crashlog:
http://pastebin.com/j7vuTSQh

I just downloaded the mod and installed it.  Does it depend on some core mod that I am missing?

**Comment by raoulvdberge** [comment]
Some other mod is messing with the CoFH API...

**Comment by PrinceOfAmber** [comment]
But as soon as I remove refinedstorage,  and change nothing else, the game starts up fine. 

 It appears to me that refinedstorage/item/ItemWirelessGrid uses cofh/api or something? Not sure, ive never used COFH,....

 Regardless, i will do a new test later where refinedstorage is the only mod and nothing else is installed

**Comment by raoulvdberge** [comment]
That means nothing... that just means that other mods that you have installed don't use that specific feature / class from the CoFH API. If you'd install a mod that use ItemEnergyContainer, it'll crash as well.

Anyhow, I've been getting a lot of reports of people complaining about an unbundled ItemEnergyContainer, so I'll just remove usages of it and implement the interface (just so it won't crash because other mods do it wrong)

**Comment by PrinceOfAmber** [comment]
Sorry to bother you.  

Yes you are correct, i did a fresh instance of forge with only this one mod installed and it works fine 100% not your code.  

Thanks for the really quick response too.  You are doing good work.

**Comment by PrinceOfAmber** [comment]
For reference, I did find the other mod that was causing the problem: In the crash log there is a column of "UE" for unloaded error, or "UC" for non errors.

Since the mod " notenoughwands-1.9.4-1.3.5 " is the only other one that had a UE, i knew that was the problem .  And sure enough, i removed notenough wands and everything works great.  So TIL how to figure out which mods are conflicting.

Of course i dont expect you to fix this, i just wanted to document it in case anyone else runs into this or something similar

**Comment by raoulvdberge** [comment]
Good to hear you found the issue!
