### ISSUE TITLE
Interface Funkiness

### ISSUE THREAD

**Issue by msrEagle** [raoulvdberge/refinedstorage#224]
Interfaces can only accept items from the top, and be extracted from the bottom. This is really weird behaviour, and makes automation a pain.

In addition, I was able to pump items into the bottom of an interface and the items ended up in the "exported items" slots of the interface.

Also, connecting an interface to a system by connecting a cable along the line from an external storage can cause the interface to not connect at all. EDIT - Chunk unloading also causes it to disconnect.

**Comment by gr4y** [comment]
I tried to use the interface myself to automate Mekanism Metallurgic Infuser and it didn't work at all, because Mekanisms Pipes won't connect to the interface, nor the ex- and/or importer. I just placed a chest on top of an Interface and dropped Dirt into it and it wasn't imported. 

Then I configured the Exporter of the Interface to give me 5 Stone Bricks, but the Chest on the top of the interface just stayed empty. So I put the Chest to the right, the left, the right and in the front of the interface, but it stayed empty. 

![2016-07-27_16 40 30](https://cloud.githubusercontent.com/assets/230350/17179325/11f284c2-5419-11e6-8231-d23eec3fc499.png)

![2016-07-27_16 40 33](https://cloud.githubusercontent.com/assets/230350/17179324/11eb8334-5419-11e6-807b-1469aa545e20.png)

**Comment by raoulvdberge** [comment]
@gr4y You have to pump the items out of the interface... (it doesn't auto eject)

And Mekanism pipes do not work on RS blocks because they do not support Forge's item handler system yet.

**Comment by raoulvdberge** [comment]
@msrEagle 
> Interfaces can only accept items from the top, and be extracted from the bottom. This is really weird behaviour, and makes automation a pain.

What do you propose instead? Interfaces can take from any side items besides the bottom side. The bottom side is meant for output.

**Comment by msrEagle** [comment]
> What do you propose instead? Interfaces can take from any side items besides the bottom side. The bottom side is meant for output.

Being able to insert/extract from any side, just like AE interfaces.

**Comment by raoulvdberge** [comment]
I have to revert this, the current way I'm doing it is broken and there is no way for me to know from the getCapability call if an insert or extract is requested
