### ISSUE TITLE
Disk crash

### ISSUE THREAD

**Issue by bigenergy** [raoulvdberge/refinedstorage#2272]
#### Issue description:
Crash client

#### Steps to reproduce:
1. No info
...

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.12.2
- Forge: 14.23.5.2838
- Refined Storage: 1.6.15

Does this issue occur on a server? [yes/no] yes

#### If a (crash)log is relevant for this issue, link it here:

https://paste.dimdev.org/owuloporoy.mccrash

**Comment by Darkere** [comment]
A disk drive was rotated downwards which is not supposed to be possible. Any idea on how that happened?

**Comment by bigenergy** [comment]
Maybe Yeta Key from Ender IO?

**Comment by bigenergy** [comment]
I put the drive by pressing the right mouse click with it in my hand on the wall. If you look at it, the game crashes.

**Comment by raoulvdberge** [comment]
Sorry I really need reproduction steps.

**Comment by KiralyCraft** [comment]
I came across this too, so posting here instead of opening a new issue.

# Screenshot
https://imgur.com/a/D5O3RLM
The problematic disk drive was placed on the cobblestone in the image, upon looking at it, it would crash. The first image is when I've removed the drive with worldedit.
The second image shows where I would stand after /home-ing into the player's house that had this issue.
The third image shows both drives, the one on the left (red) was the problematic one).
# How it happened

The player said he simply placed the drive down, and it crashed his game. When I logged in, it crashed mine as well.

# Log
See line 12829 of the full file: https://gist.github.com/KiralyCraft/ac51177689bca5c0150e0ea899e5cf8d

# Extra details
The crash still occurs without Optifine and without foamfix

Minecraft: 1.12.2
Forge: forge-1.12.2-14.23.5.2847-universal
Refined Storage: refinedstorage-1.6.15.jar

The crash occurs on the client.
The clients (both mine and the player's) are running FTB Revelation 3.2.1, unmodified. Only addition was Optifine, without which the game crashes too.

**Comment by raoulvdberge** [comment]
You need to create a new issue and just link the crashreport, not a 12k loc log file.
