### ISSUE TITLE
Disk drive not working

### ISSUE THREAD

**Issue by kuba21333** [raoulvdberge/refinedstorage#2402]
Issue description:
When i log on my world the disk drive is not working. You can't see the 3D texture of drives sticking out and it doesn't consume any rf/fe. the items that are on the disks don't show up either.

What happens:
Items don't show up in the grid and the 3D texture doesn't show up as well.

What you expected to happen:
Items should show up in the grid and the texture should appear.

 Steps to reproduce:
1. I changed some options in BetterFPS mod.
2. Restarted game.
3. Changed options back to normal.
4. Restarted game (again)
5. Played some time.
6. saved and quited the game.

Version (make sure you are on the latest version before reporting):

- Minecraft:1.12.2
- Forge:1.12.2-14.23.5.2847
- Refined Storage:1.6.15

Does this issue occur on a server? [yes/no]
no

**Comment by Darkere** [comment]
When you open the disk drive do the disks show 0/0 items?

**Comment by kuba21333** [comment]
> When you open the disk drive do the disks show 0/0 items?

Yes, it says that. I tried new disks and they work normal. I tried disk manipulator to tranfer items but that didn't work either. Can i somehow get my items back?

**Comment by Darkere** [comment]
This happens when the disk file gets corrupted. Due to poweroutage/taskmanager kill and similar. 
The only way to get the disks back is to grab the file from a backup.

Remove all the items from the new disks you made. Shut down the game and from a backup grab the <worldname>/data/refinedstorage_disks.dat. Put that in the same place in your current world.

**Comment by kuba21333** [comment]
Thanks for help. Now i know to always make backups.
