### ISSUE TITLE
Reading incorrect values on Mekanism Bins

### ISSUE THREAD

**Issue by winsrp** [raoulvdberge/refinedstorage#2442]
#### Issue description:

Mekanism Bins are show to be over capacity when in fact they have still lots of room left

#### What happens:

Percentage shows way over 100% (see screenshot), items not routed to container

#### What you expected to happen:

Show correct percentage, route items to bin

#### Steps to reproduce:
1. Place Bin (fill it above 64 items, which seems that is the max it reads for them, any type works the same)
2. Hook RS with External Storage connector from the front
3. Check External storage connector values (see screenshot)

#### Version (make sure you are on the latest version before reporting):

Minecraft: 1.15.2
Forge: 31.1.14
Refined Storage: 1.8.1
Mekanism 9.9.11

Does this issue occur on a server? don't know using single player hardcore.

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]
![image](https://user-images.githubusercontent.com/13665046/75508201-f7809b80-59a8-11ea-9c1c-aea52095ea6b.png)

**Comment by winsrp** [comment]
Fun fact I noticed, if all normal containers are full (chests), and there is a bin for a given item hooked to the network, and you try to enter items from the grid, it will successfully push them to the bin even when it wasn't doing it before regardless of priority.

**Comment by Darkere** [comment]
The visual indicator is just that visual. It does not have any influence on whether or not items may be inserted or not. Please double-check if the external storage is working. 

Make sure you are using the filter options correctly. If I'm seeing that correctly you are blacklisting iron ore from being inserted.

**Comment by winsrp** [comment]
yeah that was my bad, items are coming in one I whitelist it, but the visual bug is still there, not sure why raoul is so angry at closing issues, while the bug is still there... ¯\_(ツ)_/¯

**Comment by Darkere** [comment]
The visual representation that you see is what the mekanism bin reports as it's inventory. There is no way for RS to fix that.

**Comment by winsrp** [comment]
lest see, can I link the owner of mekanism in here @pupnewfster ?

**Comment by pupnewfster** [comment]
First off, I am not the owner of Mekanism, that would be aidan, I am just one of the maintainers.

Also my guess is this has to do with the fact that Mekanism bins only have a singular slot that it allows to go way past the max stack size of stack, and in which we manually handle the extra syncing of size so that it gets sent to the client/saved of the "size override" so that the number does not get truncated when it goes past 127.

This "issue" would seem to be due to this [line](https://github.com/raoulvdberge/refinedstorage/blob/0b35a5337ad087d6d9d61560f82f603b9bcc1143/src/main/java/com/raoulvdberge/refinedstorage/apiimpl/storage/externalstorage/ItemExternalStorage.java#L57) where it also caps the capacity of the slot at the max stack size of the stored stack. So in our case this is making refined storage display that our bins only have a max capacity of 64.

**Comment by winsrp** [comment]
Not sure why people is so angry about this post I'm just trying to help.... So yeah know everyone knows about it... I'm out... Peace.
