### ISSUE TITLE
Remove Creative Controller and Creative Wireless Grid

### ISSUE THREAD

**Issue by raoulvdberge** [raoulvdberge/refinedstorage#306]
"usesEnergy" bool in config should be used instead to disable energy usage

**Comment by TeamSpen210** [comment]
Creative items are still useful otherwise, if you want to make one particular thing have no upkeep cost while allowing the player to still craft ones that require power. Perhaps making them have some more restrictions when used by non-creative players might make them more useful - make the Controller indestructable, and prevent pairing the Wireless Grid unless the player is in Creative. That way players could be given a remote that only works for a particular system (and is useless otherwise). It could be useful for custom maps or the like.

**Comment by raoulvdberge** [comment]
Actually, you have a point. I won't be doing this.
