### ISSUE TITLE
buggy network chunk unloading crafting network

### ISSUE THREAD

**Issue by ilordnightmarei** [raoulvdberge/refinedstorage#310]
#### What happens: leave loaded chunk area of  refined storage system and return
autocrafting dosnt respond have to break cables and reinsert  crafting patterns into crafters and   have to break controller and replace it down along with grids and crafting monitor

#### Steps to reproduce:
1.leave  chunks that the storage systems in let them unload
2.go back to storage system and try to autocraft somthing nothing happens
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge:12.18.1.2073
- Refined Storage:0.9.3

Does this issue occur on a server? [yes/no]yes

#### If a (crash)log is relevant for this issue, link it here: 
not relevant
[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Should be fixed in 809baddd88535309a76be2214b2082a8ec5b5755

**Comment by psychofad** [comment]
will this also fix the issues with the transmitter and receiver blocks losing connection on login/dimension change on a server?  I have had to set up redstone reset buttons to overcome this in the current version, but would really like for it to just work.  This is especially annoying when using the interdimensional upgrade since it loses connection when traveling to the other dimension.  I have set up a wireless redstone button using RFTools that sends a redstone signal to the transmitter block in the overworld and set it's redstone setting to work without a signal so that when it gets one it forces a reconnect in the mean time, but that's just a band-aid.  If this is not covered in this fix let me know and I will create a seperate issue for it.

**Comment by raoulvdberge** [comment]
Are you chunkloading both places?

**Comment by psychofad** [comment]
Yes, I am using a chunkloader from the Persistent Bits mod that covers a 7x7 area on both ends.  I haven't tried any other chunkloaders, but I would assume that they all work the same way.  I am seeing this disconnect  issue with 2 of my Transmitter/Receiver pairs, one is in the same dimension just 3 chunks away, and the other is in another dimension, however I have a 3rd pair that is only 2 chunks away and it seems to never lose connection.  Everything is chunkloaded.

**Comment by raoulvdberge** [comment]
Then this might fix it, yes

**Comment by psychofad** [comment]
This will be in the 1.0 release correct?  Will the version on Bintray work or do I need to wait on an actual release on CurseForge?

**Comment by raoulvdberge** [comment]
wait on release, bintray are non-obfuscated builds
