### ISSUE TITLE
External Storage Doesn't Work With Mekanism's Bins

### ISSUE THREAD

**Issue by JathTyki** [raoulvdberge/refinedstorage#314]
#### Steps to reproduce:
1. Get Grid and Mekanism bin
2. Attach External Storage to Mekanism bin and configure with priority and item of desire (used sand, dirt, and cobble in this case)
3. Put item in network and it won't export to container, and if already in container, won't show in the network.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2076
- Refined Storage: 0.9.4

Does this issue occur on a server? [yes/no] Yes

#### If a (crash)log is relevant for this issue, link it here: N/A

[pastebin/gist/etc link here]

**Comment by Gepett0** [comment]
Hi,
did you pay attention to the bins only accepting items from top and provide through bottom?

YS

**Comment by JathTyki** [comment]
I didn't have the chance to respond to this, but yes. I did pay attention to that and it didn't help.

**Comment by raoulvdberge** [comment]
The bins are incompatible with RS by nature: they have different sides configured for input / output. RS needs to have both in / out access on 1 side.

So this could be fixed with some API: The deep storage unit API from MFR. Mekanism already uses this, but only if MFR is installed. And since MFR doesn't exist on 1.10.2, their DSU integration would never work.

So, this should be fixed at Mekanisms side by enabling DSU support even MFR is not installed.
