### ISSUE TITLE
Optimize autocrafting

### ISSUE THREAD

**Issue by Californ1a** [raoulvdberge/refinedstorage#412]
Say you have patterns for:

1. 1 Iron ore --(crush)--> 2 Crushed Iron
2. 1 Crushed Iron --(furnace)--> 1 Iron Ingot
3. 4 Iron Ingot --(craft)--> 1 Iron Boots

And then you want to request the system craft 5 pairs of boots.

Currently it goes through each item individually (1st pair of boots , then 2nd pair, etc), and lists each of them individually in the crafting monitor (which makes quite a long list if you're requesting a stack of something). Would it be possible to "optimize" the process by getting the total number of each base material needed before starting the crafting? Then, using the above example, the system could send all 10 Iron Ore to the crusher at once so it stacks in the crusher and the crusher would have no wait/hang time between waiting for new materials to come from the crafter.

A better example of this would be when crafting basic circuits from IC2, it individually extracts rubber from stockpiled sticky resin rather than compiling all required sticky resin before sending it to the extractor, thus causing extra hang time for the extractor.

**Comment by JohnC94** [comment]
To add on to this. Would it be possible to have crafting jobs split evenly (or as evenly as possible) across all available crafters that have the required recipe? If I tell my system to craft 20 Printed Silicon and I have 3 crafters with a processing pattern for Silicon -> Printed Silicon, the system could send 7 Silicon to 2 crafters and 6 silicon to the third instead of 20 silicon going to one crafter.

**Comment by raoulvdberge** [comment]
This is fixed with the new crafting system!
