### ISSUE TITLE
Feature request: ProjectE Integration

### ISSUE THREAD

**Issue by Gepett0** [raoulvdberge/refinedstorage#425]
Hi,
could you maybe provide a feature like in this mod?
[Equivalent Exchange](https://mods.curse.com/mc-mods/minecraft/231853-equivalent-energistics)

Sincerly

**Comment by LousyLynx** [comment]
I am pretty sure that the only thing you would need to do, @raoulvdberge is add ProjectE as a library, then add support for the solderer, because that is the only new crafting type that is added. I think that the way it works, is it checks things like ore spawn rates, and such, adds a value, and basically combines that when crafting, or smelting, or similar methods. **NOTE:** I **THINK** this is how this works...

**Comment by way2muchnoise** [comment]
That seems like something either Project E or EE should implement. Or an addon mod.
