### ISSUE TITLE
[1.2-beta2] Cascading recipes can't be crafted but dependent recipe crafts just fine

### ISSUE THREAD

**Issue by choekstr** [raoulvdberge/refinedstorage#509]
#### Issue description:

If I try to craft a Mekanism induction cell with a prerequisite of a basic energy cell with or without oredict patterns it tells me the basic energy cell isn't available.
#### What happens:

I put the oredict recipes into a crafter and ask to craft an induction cell and it claims there are no energy cells when there are cells in RS plus there is a pattern to make more (created in 1.2-beta2).  See it happening in this video: https://youtu.be/qm_tm3xukro 
#### What you expected to happen:

Crafter uses existing (partially filled or empty energy cell) and at worst case it uses the pattern to craft a new one.
#### Steps to reproduce:
1. Create oredict enabled recipe for basic energy cell
2. Create oredict enabled recipe for basic induction cell
3. Try to craft basic induction cell
   ...
#### Version (Make sure you are on the latest version before reporting):
- Minecraft: 1.10.2
- Forge: 12.18.1.2095
- Refined Storage: 1.2-beta2

Does this issue occur on a server? [yes/no]
Yes
#### If a (crash)log is relevant for this issue, link it here:

NA

**Comment by InusualZ** [comment]
We have discussed that bug. We have come to the conclusion that is a problem related to Mekanism. Instead of creating the crafting pattern directly from JEI, make the pattern manually. You would encounter another problem. If you try to create the Ultimate Energy Cube from the ground. It will get stuck crafting up to the Advanced tier. You have to cancel the crafting task and start it again just to get stuck again in the next tier :(

**Comment by acidjazz** [comment]
@InusualZ why would it be a problem w/ Mekanism when all of this works flawlessly in AE2 no matter which way you make the pattern, also the rftools crafter doesn't have this problem at all.  The problem is most likely in RS reading metadata incorrectly, same reason it stops at the advanced tier.  I'm guessing it has to do w/ metadata related to how charged the tablet is.

**Comment by way2muchnoise** [comment]
@acidjazz then just go ahead an use any other system to autocraft them -.- we know it is an issue and we are looking into solving it. But it is game breaking so it is just not a priority atm.

**Comment by acidjazz** [comment]
@way2muchnoise didn't mean to insult, <3'ing RS.  just trying to help pinpoint and solve the issues.

**Comment by choekstr** [comment]
The baby isn't fat, it's just big boned.  :)

Thanks way2muchnoise and Raoul, just making sure you guys know of the issue and understand Mekanism has been problematic for a while now.  If you guys can sort the issue that would be brilliant and much appreciated but understand if it is concluded to be an issue on Mekanism's side.  Hopefully it is just an NBT issue as that is what it feels like when it isn't matching an item it just made or has made in the past.  *fingers crossed it is easy to resolve*.

**Comment by FnordMan** [comment]
FYI: Also getting the same issue here with the Mekanism steel processing chain. It won't automatically zing through the steps to make steel.

**Comment by InusualZ** [comment]
Did you tried the last beta (Beta-6)?

**Comment by way2muchnoise** [comment]
Just wait for beta 7, more dirty fixes for mekanism are incoming

**Comment by way2muchnoise** [comment]
![](http://puu.sh/s5fVe/6af893c5a8.png)

However you'll lose the stored energy in blocks when using RS to autocraft. But at that point you should care about the stored RF in a cell. (Or whatever mekanism uses)
