### ISSUE TITLE
Autocrafting with tools creates too many tools

### ISSUE THREAD

**Issue by Cycomantis** [raoulvdberge/refinedstorage#519]
#### Steps to reproduce:
1. Add patterns for both Iron Plates and the Forge Hammer to a crafter.
2. Request 20 Iron Plates to be crafted.
3. Observe the 20 Forge Hammers in inventory and notice they all have only been used once.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2099
- Refined Storage: 1.2-beta2

Does this issue occur on a server? [yes/no] No SSP

#### If a (crash)log is relevant for this issue, link it here: NA

[pastebin/gist/etc link here]

**Comment by tivec** [comment]
Perhaps a "ignore Metadata" and "ignore NBT" could be of use in the pattern grid and pattern encoder?

**Comment by RealGrep** [comment]
Probably the same issue as #510 with recipes that return an item, I would guess.

**Comment by raoulvdberge** [comment]
@Cycomantis Did you set the pattern to an oredict pattern??

**Comment by raoulvdberge** [comment]
Nope, you didn't. Can't reproduce it here.

**Comment by way2muchnoise** [comment]
@Cycomantis You need to use oredict when using tools. This makes sure to use all meta states of the hammer.

**Comment by Vahtera** [comment]
This issue is still/again present in FTB Sky Adventures at least, Refined Storage 1.6.8, Minecraft 1.12.2, IC2 2.8.101-ex112. Setting recipes for Oredict has no effect. Tried with clicking from JEI and making the recipe manually. Still trying to craft a Hammer or Clippers for each recipe (aka, only using non-damaged item). There is no button for ignoring NBT and/or metadata.

**Comment by Darkere** [comment]
Unfortunately Intended.

Raoul recently removed all code handling reusable items because it wasn't working in many cases. Use something else like a RFtools crafter for this. 

I'm still kinda hoping he sticks to his first statement of "Will find a different solution later" and not the recent "Not gonna fix it".

Although it's possible that he is waiting for 1.13 as things will change there anyway.

**Comment by thelapisfox** [comment]
This issue is still present in 1.16.5

**Comment by LockedThread** [comment]
Still present on 1.16.5
