### ISSUE TITLE
Crafting with Items that Use Durability Not Working Properly

### ISSUE THREAD

**Issue by Darkosto** [raoulvdberge/refinedstorage#541]
#### Issue description:
I just stumbled upon a Crafting Grid bug :P Looks like the crafting grid does not properly use up damage/durability when shift clicking a large number of items. The durability stays the same on the item that takes damage.

https://sx.artdude.uk/hotlink-ok/darkosto/6CCB-75be1-1477678880.mp4
#### What happens:
Item does not use durability when shift-clicking
#### Steps to reproduce:
1.
2.
3.
...

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2114
- Refined Storage: Beta 4

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
So, I didn't try with the item you were using, but I tried with the IC2 hammer to be sure *because I couldn't find anything that is wrong in the implementation on my side*.

![x](https://raoulvdberge.com/YPeqJi)

Everything with the IC2 hammer worked, which leads me to believe that something is wrong with the mod you are using.
