### ISSUE TITLE
Huge performance hit with Interface export

### ISSUE THREAD

**Issue by obuw** [raoulvdberge/refinedstorage#732]
#### Issue description:
An interface set to export 3 wood logs is causing a massive performance hit when there aren't any wood logs in the system. Turning the interface off stops the performance hit.

My setup has the logs being stored in storage drawer with an external storage on the storage controller. Then an interface is set up to export them 3 at a time, which are fed to an alloy smelter using item conduits.

When I have wood in the system, the performance is fine. But when I run out of wood, the game takes a heavy performance hit. Perhaps the interface is continously trying to export resources that don't exist?

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 12.18.2.2171
- Refined Storage: 1.2.8

Does this issue occur on a server? No, it's an SSP world.

**Comment by obuw** [comment]
Okay, this is happening with anything else I try to export through an interface as well, as long as there isn't any in the system it lags the game horribly.

Exporting with the Exporter works fine and doesn't lag in any way.

**Comment by raoulvdberge** [comment]
Try this please:

https://refinedstorage.raoulvdberge.com/wiki/profiling

**Comment by raoulvdberge** [comment]
@obuw Any update on this?

**Comment by raoulvdberge** [comment]
Closing this as @obuw is not giving us a profiling file.

**Comment by roboderpy** [comment]
https://dbot.serealia.ca/sharex/2017/03/interface_disabled.nps
https://dbot.serealia.ca/sharex/2017/03/interface_enabled.nps
Due to how greatly GitHub doesn't recognize ZIP archive as ZIP achive, i post a link.
This happens when Interface constantly exports items, e.g. processing ores after mining
![Interface](https://dbot.serealia.ca/sharex/2017/03/2017-03-04_10.58.27.png)
Mekanism constantly processes ores, interface constantly exports ores
![Injection Factory](https://dbot.serealia.ca/sharex/2017/03/javaw_2017-03-04_11-00-25.png)
![Ores](https://dbot.serealia.ca/sharex/2017/03/javaw_2017-03-04_11-01-35.png)
This creates **major** TPS lags
Note - Ores are stored in Colossal Chest with ~265 562 slots avaliable

**Comment by raoulvdberge** [comment]
Are yoh on the latest rs? Collosal chest lag issues have been fixed there.

**Comment by roboderpy** [comment]
Latest on MC 1.10.2; I just switched to MC 1.11.2 and wasn't managed to test this bug yet.
`offtopic` Also, what do you think about this? https://github.com/McJty/XNet/issues/7

**Comment by raoulvdberge** [comment]
Did you install commoncapabilities?

**Comment by roboderpy** [comment]
Yes

**Comment by raoulvdberge** [comment]
@roboderpy Don't connect the External Storage to the "Collosal Chest Interface", but to the "Collosal Chest Core".

**Comment by roboderpy** [comment]
@raoulvdberge sorry for long non answer, but connecting External Storage directly to Chest Core causes glitches. Because of my english skill, i made a video: https://dbot.serealia.ca/sharex/2017/03/d0650a33f2-2017-03-21_17-52-44.webm
