### ISSUE TITLE
Solderer books need to ignore repair NBT tag

### ISSUE THREAD

**Issue by Kruberoid** [raoulvdberge/refinedstorage#756]
I cant place enchanted book in soldener 
Cant make Silk touch upgrade 
refinedstorage-1.2.11
forge-1.10.2-12.18.3.2185-universal

**Comment by raoulvdberge** [comment]
Can't reproduce. Some other mod is causing a conflict with RS.

![x](https://raoulvdberge.com/CzgVRF)

**Comment by DuskFalls** [comment]
I made a fortune 3 book from combining fortune 2 books, and i cant place that in a solderer

Does the solderer check enchanted books for nbt? Because if so, minecraft adds the repaircost tag when you combine things in an anvil, and if the solderer expects no nbt but it has that, it wouldnt allow the book

Or am i overthinking this?

**Comment by raoulvdberge** [comment]
Aha, that might be it. Didn't test with repairing.
