### ISSUE TITLE
Ore Dictionary allows cactus green to be substituted for Lapis Lazuli

### ISSUE THREAD

**Issue by Tyler799** [raoulvdberge/refinedstorage#768]
#### Issue description:

See the title. And below. https://imgur.com/a/36nZy

#### What happens:

Cactus Green can be substituted for Lapis. And likely all dyes, if this pattern holds. 

#### What you expected to happen:

Autocrafting should never allow the much more valuable and rare lapis to be substituted with Cactus, given that it is valuable and used in many recipes.

#### Steps to reproduce:
1. Fill any RS system with only cactus green
2. Create an autocrafting pattern for Lapis Blocks with the Ore Dictionary setting turned ON
3. Request one lapis block. Watch as it makes it using only Cactus Green.

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: Build 2185
- Refined Storage: 1.2.1.1

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by way2muchnoise** [comment]
Interesting, I didn't think that was happening anymore. Just turn off oredict for now as you don't really need it. Does it actually craft it?

**Comment by Tyler799** [comment]
It does actually craft it. I crafted some Tier-3 Solar Generators from Environmental tech and was wondering why the recipe was calling for hundreds of cactus. 

I can make lapis blocks on demand now with just cactus.

**Comment by jdratlif** [comment]
I've seen similar things. Crafting cyan dye should require blue and green, but with ore dictionary, it will use any kind of dye. It made cyan dye from bone meal for me.

**Comment by way2muchnoise** [comment]
Changed a bit how the oredict stuff works. This seems to fix the issue

**Comment by Spongman** [comment]
i'm seeing this in 1.6.15, crafting Empowered Restonia Crystal Block with a processing/ore-dict pattern. The pattern contains:
- 1 Restonia Crystal Block
- 1 Rose Red
- 1 Nether Brick
- 1 Redstone (Dust)
- 1 Brick

when crafting, it substitutes '1 Lapis Lazuli; for the '1 Rose Red'. This is clearly wrong, it should be ore-dicting $dyeRed.

I want to use ore-dicting patterns because i have many sources of $dyeRed in my storage, and i don't care which one is used.
