### ISSUE TITLE
Storage Monitor/Conversion Monitor equivalents?

### ISSUE THREAD

**Issue by SoullessWaffle** [raoulvdberge/refinedstorage#804]
Applied Energistics 2 has a block called the [Storage Monitor](http://ae-mod.info/ME-Storage-Monitor/) that displays the count of an item on the network. This makes it easy to see at a glance when you're running low on certain resources. The [Conversion Monitor](http://ae-mod.info/ME-Conversion-Monitor/) is a Storage Monitor that also allows you to withdraw and store the displayed item into the network directly.

Here's a screenshot of a wall of Storage Monitors displaying the count of various items in my AE2 network:
![storage monitors](http://puu.sh/t70d6/cca41c8675.png)

It would be great to see something similar added to Refined Storage.

**Comment by Alaric323** [comment]
Greetings raoulvdberge,

Would it be possible to backport the storage monitor to 1.10.2?  I understand it's going to soon be an unfocused version for most mod developers as 1.12 is the new base, but since ExtraCells doesn't exist for 1.10 yet, AE2 doesn't support liquid storage.

Sorry for such an inconvenient request; I fully understand your decision to not do so.  I'll figure out another way otherwise.

**Comment by raoulvdberge** [comment]
No.

**Comment by Alaric323** [comment]
Understood, thanks anyway.
