### ISSUE TITLE
Autocrafting of chance-based processing recipes

### ISSUE THREAD

**Issue by SoullessWaffle** [raoulvdberge/refinedstorage#805]
Some processing recipes have outputs which are not guaranteed.
For example, the Ender IO SAG Mill can grind Sand into Silicon, but with a 50% chance of producing output:
![ender io sag mill sand to silicon recipe](http://puu.sh/t70Ak/34eaf42a82.png)

Another example, the SAG Mill can grind Coal into Coal Powder with a 10% chance of producing some extra IC2 Sulfur Dust:
![ender io sag mill coal to sulfur recipe](http://puu.sh/t71cq/d1776b9c39.png)

Is there a way to define this in Processing Patterns? In the specific case of Silicon I would like Refined Storage to keep sending Sand to my SAG Mills until enough Silicon is produced to complete the crafting job.
For more expensive recipes I can imagine the player might want to set some sort of limit to make sure they don't burn through all their resources trying to complete a crafting job.

**Comment by way2muchnoise** [comment]
Defining it in a processing pattern is kinda hard. You could do like 3 or 4 sand for 1 silicon. Which will stop inserting sand once it gets the required silicon. But might get stuck at some point. You could hope the rescheduling kicks in but that chance is rather small since it will have started a task and be waiting for it to finish. Or you could setup an exporter with a [detector](https://refinedstorage.raoulvdberge.com/wiki/detector) to keep a certain amount of silicon stocked.

Adding something that can handle percentage based stuff would need a lot of work on how processing patterns get written. And how they get processed while autocrafting.

**Comment by raoulvdberge** [comment]
I don't think this is worth it

**Comment by renzhentaxi** [comment]
I would just ignore the extra goodies and only put down the things I know i will get 100% of the time.
