### ISSUE TITLE
[1.11] Crafting grid auto rotates north when not in chunkloaded area then coming back.

### ISSUE THREAD

**Issue by shortybsd** [raoulvdberge/refinedstorage#897]
Minecraft 1.11
Forge 2199
Refined Storage 1.3.5
Runs on a dedicated server

When leaving my main spot then coming back after a while, the Crafting Grid and Disk Manipulator all will be rotated facing north. Really odd error as it recently started doing it.

**Comment by raoulvdberge** [comment]
Any logs?

**Comment by Darkosto** [comment]
This actually happens to External Storage in 1.10.2: 
http://imgur.com/oGzxsVv
https://sx.artdude.uk/hotlink-ok/darkosto/Aclu-4951c-1484788700.png

They function properly, from what I can tell. But the blocks just completely turned around. It happens when I leave and join my server. There seem to be no logs from my initial scan of the output.

RS: 1.2.17
Forge: 2215 and 2221

**Comment by raoulvdberge** [comment]
This happens when a chunk read failed, most likely caused by an other mod.

**Comment by raoulvdberge** [comment]
More specifically: another tile entity failed NBT read, causing all the other tile entities in the same chunk not reading their data, making the External Storage face the default facing.

For an example of this, see #890

**Comment by shortybsd** [comment]
I've updated a few mods and removed items touching or placed next to the Refined Storage blocks. All seems good so far. There was no errors in my logs from client or server.

**Comment by raoulvdberge** [comment]
This is not an RS issue.
