### ISSUE TITLE
craft-only exporter

### ISSUE THREAD

**Issue by blackdrag** [raoulvdberge/refinedstorage#965]
#### Issue description:
autocrafting using an exporter and a crafting card with the target inventory being something monitored by refined storage will lead to an item-loop

#### What happens:
item-loop.

#### What you expected to happen:
no item-loop and only crafting the items

#### Steps to reproduce:
1. load sf3 and get iron essence plants
2. make an "8 essence to 1 ingot" recipe
3. make a network monitoring a chest via external storage
4. let an exporter with crafting card export to the chest

#### Version (Make sure you are on the latest version before reporting):
- SkyFactory 3
- Minecraft: 1.10.2
- Forge:  12.18.3.2215
- Refined Storage: 1.2.18

Does this issue occur on a server? yes

**Comment by raoulvdberge** [comment]
That's not a issue at all, this is intended behavior. Change the priority of the External Storage bus.

**Comment by blackdrag** [comment]
tried that, no luck

**Comment by Amegatron** [comment]
Sorry for necro-posting, but problem described in this issue is still actual. And the actual problem is in trying to make a buffered storage. Imagine I have a single grid, where, for simplicity, I already have some sand, and I already have a auto-craft recipe for making glass. Assume also that making glass is very time-consuming, so I would like to have a buffer in this same grid with, say, 10 stacks of glass. As soon as the amount goes below this threshold, the system needs to auto-craft the missing using the recipe in this same grid. Even now this seems to still not be possible, or I'll be thankful for a solution.

What was meant by @blackdrag (If I understand correctly and it corresponds to my own problem), this problem could be solved if an exporter could export items only by crafting them. For example, I could have an exporter to any other storage (chest, for example), which would export glass but only by crafting it. I would also connect that chest as an external storage. So, assuming I want to have a full chest of glass as a buffer, this scheme will work. Instead, no matter what storage priorities are, exporter will always loop the already existing items in that chest, never reaching the needed amount.
