### ISSUE TITLE
Crafter doesn't work with brewing stand?

### ISSUE THREAD

**Issue by AlexiyOrlov** [raoulvdberge/refinedstorage#992]
#### Issue description:
Can't automate brewing stand.
#### What happens:
The crafter doesn't work with brewing stand.
#### What you expected to happen:
I expect the crafter to be able to make potions.
#### Steps to reproduce:
1. Make a processing pattern for a potion.
2. Put the pattern into crafter which is facing a brewing stand.
3. Request potion from grid.
4. The Crafting monitor tells 'machine is in use', but brewing stand doesn't do anything.

#### Version:

- Minecraft: 1.10.2
- Forge: 12.8.3.2185
- Refined Storage: 1.2.21

**Comment by raoulvdberge** [comment]
For autocrafting to work the Crafter has to be able to insert *all* items. As soon as one item can't enter, which is the case with brewing stands, the Crafter will block.

What I recommend is to connect the Crafter to a hopper instead of to the brewing stand immediately.

**Comment by leoXplod** [comment]
Hi, good afternoon!

Could you help me somehow?

My game crashed while i tried to connect a cable into an exporter, the exporter was connected into a brewing stand... Since then, I can´t open the map anymore, and my last backup were somedays ago.

[crash-2020-05-03_15.55.30-server.txt](https://github.com/raoulvdberge/refinedstorage/files/4571451/crash-2020-05-03_15.55.30-server.txt)

**Comment by leoXplod** [comment]
One more thing:

Congratulations for the mod, an elegant (and Refined) idea to magane items in the MC, Nice job!!!

**Comment by raoulvdberge** [comment]
Please create a new issue and upload the crashreport on pastebin or gist. Not as a file download.

**Comment by leoXplod** [comment]
Sorry, my mistake, Going to do that
